# Generated by Django 3.1.4 on 2021-03-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210212_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(default='Unknown', verbose_name='Имя пользователя'),
        ),
    ]
