# Generated by Django 3.1.4 on 2021-03-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20210311_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщений'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профилей'},
        ),
    ]
