# Generated by Django 3.1.4 on 2021-04-07 08:02

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210319_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_cat', to='products.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=products.models.get_sentinel_category, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ozone_id',
            field=models.CharField(max_length=200, verbose_name='Артикул OZONE'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
    ]
