# Generated by Django 3.1.4 on 2021-04-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210407_0802'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='category',
            order_with_respect_to='parent',
        ),
    ]
